parser: '@typescript-eslint/parser'
extends:
  - prettier
ignorePatterns:
  - dist
  - node_modules
parserOptions:
  sourceType: module
env:
  node: true
  # Not a real browser, but jsdom is available.
  # This is good enough.
  browser: true
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  global-require: 0
  'prettier/prettier': 'error'
